//! Z3 Solver FFI Bridge & Execution Engine.
//!
//! This module provides a robust interface to Z3 for solving SMT-LIB2 scripts
//! generated by the lowering engine. It supports incremental solving, model
//! extraction, unsat core extraction, and resource limits.

#[cfg(feature = "z3")]
use crate::config::{Logic, SolverConfig};
#[cfg(feature = "z3")]
use crate::error::{SolverError, VerifyError};
#[cfg(feature = "z3")]
use crate::model::{Model, UnsatCore};
#[cfg(feature = "z3")]
use crate::smtlib::Script;
#[cfg(feature = "z3")]
use std::collections::HashMap;
#[cfg(feature = "z3")]
use std::sync::Arc;
#[cfg(feature = "z3")]
use std::time::{Duration, Instant};

/// Verification result from the solver.
#[cfg(feature = "z3")]
#[derive(Debug, Clone)]
pub enum VerifyResult {
    /// Satisfiable with a model.
    Sat(Model),
    /// Unsatisfiable with optional unsat core.
    Unsat(Option<UnsatCore>),
    /// Unknown (incomplete theory, timeout, etc.).
    Unknown(String),
    /// Error during solving.
    Error(String),
}

impl VerifyResult {
    pub fn is_sat(&self) -> bool {
        matches!(self, VerifyResult::Sat(_))
    }

    pub fn is_unsat(&self) -> bool {
        matches!(self, VerifyResult::Unsat(_))
    }

    pub fn is_unknown(&self) -> bool {
        matches!(self, VerifyResult::Unknown(_))
    }

    pub fn is_error(&self) -> bool {
        matches!(self, VerifyResult::Error(_))
    }

    pub fn model(&self) -> Option<&Model> {
        match self {
            VerifyResult::Sat(m) => Some(m),
            _ => None,
        }
    }

    pub fn unsat_core(&self) -> Option<&UnsatCore> {
        match self {
            VerifyResult::Unsat(Some(core)) => Some(core),
            _ => None,
        }
    }
}
#[cfg(feature = "z3")]

/// Z3 solver wrapper with context management.
#[cfg(feature = "z3")]
pub struct Solver {
    config: SolverConfig,
    context: Option<z3::Context>,
    solver: Option<z3::Solver>,
    incremental_level: u32,
    assertion_ids: HashMap<String, usize>, // Named assertions for unsat core
    next_assertion_id: usize,
}
#[cfg(feature = "z3")]

impl Solver {
    /// Create a new solver with the given configuration.
    pub fn new(config: SolverConfig) -> Result<Self, VerifyError> {
        let ctx = Self::create_context(&config)?;
        let solver = Self::create_solver(&ctx, &config)?;

        Ok(Self {
            config,
            context: Some(ctx),
            solver: Some(solver),
            incremental_level: 0,
            assertion_ids: HashMap::new(),
            next_assertion_id: 0,
        })
    }

    /// Create Z3 context with configuration.
    fn create_context(config: &SolverConfig) -> Result<z3::Context, VerifyError> {
        // Use thread-local context and configure it
        let mut ctx = z3::Context::thread_local();

        // Set logic
        ctx.update_param_value("logic", config.logic.as_str());

        // Set timeout
        ctx.update_param_value("timeout", &config.timeout.as_millis().to_string());

        // Set memory limit (advisory)
        ctx.update_param_value("memory_limit", &config.memory_mb.to_string());

        // Set random seed for reproducibility
        if let Some(seed) = config.seed {
            ctx.update_param_value("random_seed", &seed.to_string());
        }

        // Set number of threads
        if config.threads > 0 {
            ctx.update_param_value("parallel.enable", "true");
            ctx.update_param_value("parallel.threads_max", &config.threads.to_string());
        }

        // Enable model generation
        ctx.update_param_value(
            "model",
            if config.produce_models {
                "true"
            } else {
                "false"
            },
        );

        // Enable unsat core generation
        ctx.update_param_value(
            "unsat_core",
            if config.produce_unsat_cores {
                "true"
            } else {
                "false"
            },
        );

        Ok(ctx)
    }

    /// Create Z3 solver from context.
    fn create_solver(
        _ctx: &z3::Context,
        _config: &SolverConfig,
    ) -> Result<z3::Solver, VerifyError> {
        // Use a fresh solver for each check if not incremental
        // Logic is set via SMT-LIB2 (set-logic) in the script, not via API
        let solver = z3::Solver::new();

        Ok(solver)
    }

    /// Assert a formula (by name for unsat core tracking).
    pub fn assert_named(&mut self, name: &str, formula: &z3::ast::Bool) -> Result<(), VerifyError> {
        let solver = self.solver.as_mut().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?;

        let id = self.next_assertion_id;
        self.next_assertion_id += 1;
        self.assertion_ids.insert(name.to_string(), id);

        solver.assert(formula);
        Ok(())
    }

    /// Assert a formula without name.
    pub fn assert(&mut self, formula: &z3::ast::Bool) -> Result<(), VerifyError> {
        let solver = self.solver.as_mut().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?;

        solver.assert(formula);
        Ok(())
    }

    /// Push a new incremental level.
    pub fn push(&mut self) -> Result<(), VerifyError> {
        let solver = self.solver.as_mut().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?;

        solver.push();
        self.incremental_level += 1;
        Ok(())
    }

    /// Pop the current incremental level.
    pub fn pop(&mut self, n: u32) -> Result<(), VerifyError> {
        let solver = self.solver.as_mut().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?;

        if n > self.incremental_level {
            return Err(VerifyError::Solver(SolverError::IncrementalError(format!(
                "Cannot pop {} levels (current depth: {})",
                n, self.incremental_level
            ))));
        }

        solver.pop(n);
        self.incremental_level -= n;
        Ok(())
    }

    /// Check satisfiability with optional assumptions.
    pub fn check_sat(
        &mut self,
        assumptions: &[z3::ast::Bool],
    ) -> Result<VerifyResult, VerifyError> {
        let solver = self.solver.as_mut().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?;

        let start = Instant::now();
        let timeout = self.config.timeout;

        // Check with timeout
        let result = if assumptions.is_empty() {
            solver.check()
        } else {
            solver.check_assumptions(assumptions)
        };

        let elapsed = start.elapsed();
        if elapsed >= timeout {
            return Ok(VerifyResult::Unknown(format!(
                "Timeout after {:.2}s",
                elapsed.as_secs_f64()
            )));
        }

        match result {
            z3::SatResult::Sat => {
                let model = if self.config.produce_models {
                    Model::from_z3(solver.get_model())
                        .map_err(|e| VerifyError::Solver(SolverError::ModelExtractionFailed(e)))?
                } else {
                    Model::empty()
                };
                Ok(VerifyResult::Sat(model))
            }
            z3::SatResult::Unsat => {
                let unsat_core = if self.config.produce_unsat_cores {
                    let core = solver.get_unsat_core();
                    if core.is_empty() {
                        None
                    } else {
                        Some(UnsatCore::from_z3(core, &self.assertion_ids).map_err(|e| {
                            VerifyError::Solver(SolverError::UnsatCoreExtractionFailed(e))
                        })?)
                    }
                } else {
                    None
                };
                Ok(VerifyResult::Unsat(unsat_core))
            }
            z3::SatResult::Unknown => {
                let reason = solver
                    .get_reason_unknown()
                    .map(|s| s.to_string())
                    .unwrap_or_else(|| "Unknown reason".to_string());
                Ok(VerifyResult::Unknown(reason))
            }
        }
    }

    /// Get the Z3 context.
    pub fn context(&self) -> Option<&z3::Context> {
        self.context.as_ref()
    }

    /// Get the Z3 solver.
    pub fn solver(&self) -> Option<&z3::Solver> {
        self.solver.as_ref()
    }

    /// Reset the solver (clear all assertions).
    pub fn reset(&mut self) -> Result<(), VerifyError> {
        let ctx = self.context.as_ref().ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Context not initialized".to_string(),
            ))
        })?;

        let solver = Self::create_solver(ctx, &self.config)?;
        self.solver = Some(solver);
        self.incremental_level = 0;
        self.assertion_ids.clear();
        self.next_assertion_id = 0;
        Ok(())
    }
}
#[cfg(feature = "z3")]

/// Parse and execute an SMT-LIB2 script using Z3.
#[cfg(feature = "z3")]
pub fn verify(smt_script: &str, config: SolverConfig) -> Result<VerifyResult, VerifyError> {
    let mut solver = Solver::new(config)?;

    // Parse SMT-LIB2 script using high-level API
    solver
        .solver
        .as_mut()
        .ok_or_else(|| {
            VerifyError::Solver(SolverError::ContextFailed(
                "Solver not initialized".to_string(),
            ))
        })?
        .from_string(smt_script);

    // Check satisfiability
    solver.check_sat(&[])
}
#[cfg(feature = "z3")]

/// Execute multiple independent verification conditions in parallel.
#[cfg(feature = "z3")]
pub fn verify_parallel(
    scripts: Vec<(String, String)>, // (name, script)
    config: SolverConfig,
) -> Vec<(String, Result<VerifyResult, VerifyError>)> {
    use rayon::prelude::*;

    scripts
        .into_par_iter()
        .map(|(name, script)| {
            let result = verify(&script, config.clone());
            (name, result)
        })
        .collect()
}
#[cfg(feature = "z3")]

/// Solver statistics.
#[cfg(feature = "z3")]
#[derive(Debug, Clone, Default)]
pub struct SolverStats {
    pub total_time: Duration,
    pub sat_calls: usize,
    pub unsat_calls: usize,
    pub unknown_calls: usize,
    pub error_calls: usize,
    pub total_assertions: usize,
}
#[cfg(feature = "z3")]

impl SolverStats {
    pub fn record(&mut self, result: &VerifyResult, elapsed: Duration) {
        self.total_time += elapsed;
        match result {
            VerifyResult::Sat(_) => self.sat_calls += 1,
            VerifyResult::Unsat(_) => self.unsat_calls += 1,
            VerifyResult::Unknown(_) => self.unknown_calls += 1,
            VerifyResult::Error(_) => self.error_calls += 1,
        }
    }
}
